apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-289915
  artifacts:
    - image: us.gcr.io/ticketing-dev-289915/auth
      context: auth
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: us.gcr.io/ticketing-dev-289915/client
      context: client
      sync:
        manual:
          - src: '**/*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: us.gcr.io/ticketing-dev-289915/tickets
      context: tickets
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: us.gcr.io/ticketing-dev-289915/orders
      context: orders
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: us.gcr.io/ticketing-dev-289915/expiration
      context: expiration
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: us.gcr.io/ticketing-dev-289915/payments
      context: payments
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
